#include "MOBSCE.h"

enum MouseButtons {
	MB_LEFT,
	MB_RIGHT,
	MB_MIDDLE,
	MB_BACK,
	MB_FORWARD
};

enum MouseScroll {
    SCROLL_UP = 1,
    SCROLL_DOWN = -1,
    SCROLL_RIGHT = 1,
    SCROLL_LEFT = -1
};

enum Keys {
	K_0 = SDL_SCANCODE_0,
	K_1 = SDL_SCANCODE_1,
	K_2 = SDL_SCANCODE_2,
	K_3 = SDL_SCANCODE_3,
	K_4 = SDL_SCANCODE_4,
	K_5 = SDL_SCANCODE_5,
	K_6 = SDL_SCANCODE_6,
	K_7 = SDL_SCANCODE_7,
	K_8 = SDL_SCANCODE_8,
	K_9 = SDL_SCANCODE_9,
	K_A = SDL_SCANCODE_A,	
	K_B = SDL_SCANCODE_B,
	K_C = SDL_SCANCODE_C,
	K_D = SDL_SCANCODE_D,
	K_E = SDL_SCANCODE_E,
	K_F = SDL_SCANCODE_F,
	K_G = SDL_SCANCODE_G,
	K_H = SDL_SCANCODE_H,
	K_I = SDL_SCANCODE_I,
	K_J = SDL_SCANCODE_J,
	K_K = SDL_SCANCODE_K,
	K_L = SDL_SCANCODE_L,
	K_M = SDL_SCANCODE_M,
	K_N = SDL_SCANCODE_N,
	K_O = SDL_SCANCODE_O,
	K_P = SDL_SCANCODE_P,
	K_Q = SDL_SCANCODE_Q,
	K_R = SDL_SCANCODE_R,
	K_S = SDL_SCANCODE_S,
	K_T = SDL_SCANCODE_T,
	K_U = SDL_SCANCODE_U,
	K_V = SDL_SCANCODE_V,
	K_W = SDL_SCANCODE_W,
	K_X = SDL_SCANCODE_X,
	K_Y = SDL_SCANCODE_Y,
	K_Z = SDL_SCANCODE_Z,
	//now i know my ABCs
	//next time won't you
	//sing with me
    K_ESCAPE = SDL_SCANCODE_ESCAPE,
	K_F1 = SDL_SCANCODE_F1,
	K_F2 = SDL_SCANCODE_F2,
	K_F3 = SDL_SCANCODE_F3,
	K_F4 = SDL_SCANCODE_F4,
	K_F5 = SDL_SCANCODE_F5,
	K_F6 = SDL_SCANCODE_F6,
	K_F7 = SDL_SCANCODE_F7,
	K_F8 = SDL_SCANCODE_F8,
	K_F9 = SDL_SCANCODE_F9,
	K_F10 = SDL_SCANCODE_F10,
	K_F11 = SDL_SCANCODE_F11,
	K_F12 = SDL_SCANCODE_F12,
	K_PRINTSCREEN = SDL_SCANCODE_PRINTSCREEN,
	K_SCROLLLOCK = SDL_SCANCODE_SCROLLLOCK,
	K_PAUSE = SDL_SCANCODE_PAUSE,
	K_TILDA = SDL_SCANCODE_GRAVE,
	K_MINUS = SDL_SCANCODE_MINUS,
	K_EQUAL = SDL_SCANCODE_EQUALS,
	K_BACKSPACE = SDL_SCANCODE_BACKSPACE,
	K_INSERT = SDL_SCANCODE_INSERT,
	K_HOME = SDL_SCANCODE_HOME,
	K_PAGEUP = SDL_SCANCODE_PAGEUP,
	K_NUMLOCK = SDL_SCANCODE_NUMLOCKCLEAR,
	K_TAB = SDL_SCANCODE_TAB,
	K_OPENBRACKET = SDL_SCANCODE_LEFTBRACKET,
	K_CLOSEDBRACKET = SDL_SCANCODE_RIGHTBRACKET,
	K_BACKSLASH = SDL_SCANCODE_BACKSLASH,
	K_DELETE = SDL_SCANCODE_DELETE,
	K_END = SDL_SCANCODE_END,
	K_PAGEDOWN = SDL_SCANCODE_PAGEDOWN,
	K_CAPSLOCK = SDL_SCANCODE_CAPSLOCK,
	K_SEMICOLON = SDL_SCANCODE_SEMICOLON,
	K_APOSTROPHE = SDL_SCANCODE_APOSTROPHE,
	K_RETURN = SDL_SCANCODE_RETURN,
	K_ENTER = SDL_SCANCODE_RETURN,
	K_LEFTSHIFT = SDL_SCANCODE_LSHIFT,
	K_COMMA = SDL_SCANCODE_COMMA,
	K_PERIOD = SDL_SCANCODE_PERIOD,
	K_SLASH = SDL_SCANCODE_SLASH,
	K_RIGHTSHIFT = SDL_SCANCODE_RSHIFT,
	K_UP = SDL_SCANCODE_UP,
	K_LEFTCONTROL = SDL_SCANCODE_LCTRL,
	K_LEFTALT = SDL_SCANCODE_LALT,
	K_SPACEBAR = SDL_SCANCODE_SPACE,
	K_RIGHTALT = SDL_SCANCODE_RALT,
	K_MENU = SDL_SCANCODE_MENU,
	K_RIGHTCONTROL = SDL_SCANCODE_RCTRL,
	K_LEFT = SDL_SCANCODE_LEFT,
	K_DOWN = SDL_SCANCODE_DOWN,
	K_RIGHT = SDL_SCANCODE_RIGHT
};

enum GamepadButtons {
    GP_FB_RIGHT,
    GP_FB_BOTTOM,
    GP_FB_LEFT,
    GP_FB_TOP,
    GP_DP_UP,
    GP_DP_DOWN,
    GP_DP_LEFT,
    GP_DP_RIGHT,
    GP_FB_START,
    GP_FB_SELECT,
    GP_FB_SUPER,
    GP_BPR_LEFT,
    GP_BPR_RIGHT,
    GP_STKDWN_LEFT,
    GP_STKDWN_RIGHT
};

enum GamepadTriggers {
    GP_TRGR_LEFT,
    GP_TRGR_RIGHT
};

enum GamepadStickAxis {
    GP_STK_LEFT_X,
    GP_STK_LEFT_Y,
    GP_STK_RIGHT_X,
    GP_STK_RIGHT_Y
};

enum GamepadSticks {
    GP_STK_LEFT,
    GP_STK_RIGHT
};